<?php

namespace Database\Seeders;

use App\Models\Sourate;
use Illuminate\Database\Seeder;

class SourateSeeder extends Seeder
{
    public function run(): void
    {
        $sourates = [
            [1, 'الفاتحة', 'Al-Fatiha', 7, 'Mecquoise'],
            [2, 'البقرة', 'Al-Baqara', 286, 'Medinoise'],
            [3, 'آل عمران', 'Al-Imran', 200, 'Medinoise'],
            [4, 'النساء', 'An-Nisa', 176, 'Medinoise'],
            [5, 'المائدة', "Al-Ma'idah", 120, 'Medinoise'],
            [6, 'الأنعام', "Al-An'am", 165, 'Mecquoise'],
            [7, 'الأعراف', "Al-A'raf", 206, 'Mecquoise'],
            [8, 'الأنفال', 'Al-Anfal', 75, 'Medinoise'],
            [9, 'التوبة', 'At-Tawba', 129, 'Medinoise'],
            [10, 'يونس', 'Yunus', 109, 'Mecquoise'],
            [11, 'هود', 'Hud', 123, 'Mecquoise'],
            [12, 'يوسف', 'Yusuf', 111, 'Mecquoise'],
            [13, 'الرعد', "Ar-Ra'd", 43, 'Medinoise'],
            [14, 'إبراهيم', 'Ibrahim', 52, 'Mecquoise'],
            [15, 'الحجر', 'Al-Hijr', 99, 'Mecquoise'],
            [16, 'النحل', 'An-Nahl', 128, 'Mecquoise'],
            [17, 'الإسراء', 'Al-Isra', 111, 'Mecquoise'],
            [18, 'الكهف', 'Al-Kahf', 110, 'Mecquoise'],
            [19, 'مريم', 'Maryam', 98, 'Mecquoise'],
            [20, 'طه', 'Taha', 135, 'Mecquoise'],
            [21, 'الأنبياء', 'Al-Anbiya', 112, 'Mecquoise'],
            [22, 'الحج', 'Al-Hajj', 78, 'Medinoise'],
            [23, 'المؤمنون', "Al-Mu'minun", 118, 'Mecquoise'],
            [24, 'النور', 'An-Nur', 64, 'Medinoise'],
            [25, 'الفرقان', 'Al-Furqan', 77, 'Mecquoise'],
            [26, 'الشعراء', "Ash-Shu'ara", 227, 'Mecquoise'],
            [27, 'النمل', 'An-Naml', 93, 'Mecquoise'],
            [28, 'القصص', 'Al-Qasas', 88, 'Mecquoise'],
            [29, 'العنكبوت', "Al-'Ankabut", 69, 'Mecquoise'],
            [30, 'الروم', 'Ar-Rum', 60, 'Mecquoise'],
            [31, 'لقمان', 'Luqman', 34, 'Mecquoise'],
            [32, 'السجدة', 'As-Sajda', 30, 'Mecquoise'],
            [33, 'الأحزاب', 'Al-Ahzab', 73, 'Medinoise'],
            [34, 'سبأ', 'Saba', 54, 'Mecquoise'],
            [35, 'فاطر', 'Fatir', 45, 'Mecquoise'],
            [36, 'يس', 'Ya-Sin', 83, 'Mecquoise'],
            [37, 'الصافات', 'As-Saffat', 182, 'Mecquoise'],
            [38, 'ص', 'Sad', 88, 'Mecquoise'],
            [39, 'الزمر', 'Az-Zumar', 75, 'Mecquoise'],
            [40, 'غافر', 'Ghafir', 85, 'Mecquoise'],
            [41, 'فصلت', 'Fussilat', 54, 'Mecquoise'],
            [42, 'الشورى', 'Ash-Shura', 53, 'Mecquoise'],
            [43, 'الزخرف', 'Az-Zukhruf', 89, 'Mecquoise'],
            [44, 'الدخان', 'Ad-Dukhan', 59, 'Mecquoise'],
            [45, 'الجاثية', 'Al-Jathiya', 37, 'Mecquoise'],
            [46, 'الأحقاف', 'Al-Ahqaf', 35, 'Mecquoise'],
            [47, 'محمد', 'Muhammad', 38, 'Medinoise'],
            [48, 'الفتح', 'Al-Fath', 29, 'Medinoise'],
            [49, 'الحجرات', 'Al-Hujurat', 18, 'Medinoise'],
            [50, 'ق', 'Qaf', 45, 'Mecquoise'],
            [51, 'الذاريات', 'Adh-Dhariyat', 60, 'Mecquoise'],
            [52, 'الطور', 'At-Tur', 49, 'Mecquoise'],
            [53, 'النجم', 'An-Najm', 62, 'Mecquoise'],
            [54, 'القمر', 'Al-Qamar', 55, 'Mecquoise'],
            [55, 'الرحمن', 'Ar-Rahman', 78, 'Medinoise'],
            [56, 'الواقعة', "Al-Waqi'a", 96, 'Mecquoise'],
            [57, 'الحديد', 'Al-Hadid', 29, 'Medinoise'],
            [58, 'المجادلة', 'Al-Mujadala', 22, 'Medinoise'],
            [59, 'الحشر', 'Al-Hashr', 24, 'Medinoise'],
            [60, 'الممتحنة', 'Al-Mumtahana', 13, 'Medinoise'],
            [61, 'الصف', 'As-Saff', 14, 'Medinoise'],
            [62, 'الجمعة', "Al-Jumu'a", 11, 'Medinoise'],
            [63, 'المنافقون', 'Al-Munafiqun', 11, 'Medinoise'],
            [64, 'التغابن', 'At-Taghabun', 18, 'Medinoise'],
            [65, 'الطلاق', 'At-Talaq', 12, 'Medinoise'],
            [66, 'التحريم', 'At-Tahrim', 12, 'Medinoise'],
            [67, 'الملك', 'Al-Mulk', 30, 'Mecquoise'],
            [68, 'القلم', 'Al-Qalam', 52, 'Mecquoise'],
            [69, 'الحاقة', 'Al-Haqqa', 52, 'Mecquoise'],
            [70, 'المعارج', "Al-Ma'arij", 44, 'Mecquoise'],
            [71, 'نوح', 'Nuh', 28, 'Mecquoise'],
            [72, 'الجن', 'Al-Jinn', 28, 'Mecquoise'],
            [73, 'المزمل', 'Al-Muzzammil', 20, 'Mecquoise'],
            [74, 'المدثر', 'Al-Muddathir', 56, 'Mecquoise'],
            [75, 'القيامة', 'Al-Qiyama', 40, 'Mecquoise'],
            [76, 'الإنسان', 'Al-Insan', 31, 'Medinoise'],
            [77, 'المرسلات', 'Al-Mursalat', 50, 'Mecquoise'],
            [78, 'النبأ', 'An-Naba', 40, 'Mecquoise'],
            [79, 'النازعات', "An-Nazi'at", 46, 'Mecquoise'],
            [80, 'عبس', 'Abasa', 42, 'Mecquoise'],
            [81, 'التكوير', 'At-Takwir', 29, 'Mecquoise'],
            [82, 'الانفطار', 'Al-Infitar', 19, 'Mecquoise'],
            [83, 'المطففين', 'Al-Mutaffifin', 36, 'Mecquoise'],
            [84, 'الانشقاق', 'Al-Inshiqaq', 25, 'Mecquoise'],
            [85, 'البروج', 'Al-Buruj', 22, 'Mecquoise'],
            [86, 'الطارق', 'At-Tariq', 17, 'Mecquoise'],
            [87, 'الأعلى', "Al-A'la", 19, 'Mecquoise'],
            [88, 'الغاشية', 'Al-Ghashiya', 26, 'Mecquoise'],
            [89, 'الفجر', 'Al-Fajr', 30, 'Mecquoise'],
            [90, 'البلد', 'Al-Balad', 20, 'Mecquoise'],
            [91, 'الشمس', 'Ash-Shams', 15, 'Mecquoise'],
            [92, 'الليل', 'Al-Layl', 21, 'Mecquoise'],
            [93, 'الضحى', 'Ad-Duha', 11, 'Mecquoise'],
            [94, 'الشرح', 'Ash-Sharh', 8, 'Mecquoise'],
            [95, 'التين', 'At-Tin', 8, 'Mecquoise'],
            [96, 'العلق', 'Al-Alaq', 19, 'Mecquoise'],
            [97, 'القدر', 'Al-Qadr', 5, 'Mecquoise'],
            [98, 'البينة', 'Al-Bayyina', 8, 'Medinoise'],
            [99, 'الزلزلة', 'Az-Zalzala', 8, 'Medinoise'],
            [100, 'العاديات', 'Al-Adiyat', 11, 'Mecquoise'],
            [101, 'القارعة', "Al-Qari'a", 11, 'Mecquoise'],
            [102, 'التكاثر', 'At-Takathur', 8, 'Mecquoise'],
            [103, 'العصر', 'Al-Asr', 3, 'Mecquoise'],
            [104, 'الهمزة', 'Al-Humaza', 9, 'Mecquoise'],
            [105, 'الفيل', 'Al-Fil', 5, 'Mecquoise'],
            [106, 'قريش', 'Quraysh', 4, 'Mecquoise'],
            [107, 'الماعون', "Al-Ma'un", 7, 'Mecquoise'],
            [108, 'الكوثر', 'Al-Kawthar', 3, 'Mecquoise'],
            [109, 'الكافرون', 'Al-Kafirun', 6, 'Mecquoise'],
            [110, 'النصر', 'An-Nasr', 3, 'Medinoise'],
            [111, 'المسد', 'Al-Masad', 5, 'Mecquoise'],
            [112, 'الإخلاص', 'Al-Ikhlas', 4, 'Mecquoise'],
            [113, 'الفلق', 'Al-Falaq', 5, 'Mecquoise'],
            [114, 'الناس', 'An-Nas', 6, 'Mecquoise'],
        ];

        foreach ($sourates as [$numero, $nomArabe, $nomFrancais, $nombreVersets, $revelation]) {
            Sourate::updateOrCreate(
                ['numero' => $numero],
                [
                    'nom_arabe' => $nomArabe,
                    'nom_francais' => $nomFrancais,
                    'nombre_versets' => $nombreVersets,
                    'revelation' => $revelation,
                ]
            );
        }
    }
}
